// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML;

namespace OWT; 

public partial class MLModel
{
    /// <summary>
    ///     Retrains model using the pipeline generated as part of the training process. For more information on how to load
    ///     data, see aka.ms/loaddata.
    /// </summary>
    /// <param name="mlContext"></param>
    /// <param name="trainData"></param>
    /// <returns></returns>
    public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
    {
        var pipeline = BuildPipeline(mlContext);
        var model = pipeline.Fit(trainData);

        return model;
    }

    /// <summary>
    ///     build the pipeline that is used from model builder. Use this function to retrain model.
    /// </summary>
    /// <param name="mlContext"></param>
    /// <returns></returns>
    public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
    {
        // Data process configuration with pipeline data transformations
        var pipeline = mlContext.Forecasting.ForecastBySsa(windowSize: 170, seriesLength: 3604, trainSize: 98338,
            horizon: 100, outputColumnName: @"col3", inputColumnName: @"col3", confidenceLowerBoundColumn: @"col3_LB",
            confidenceUpperBoundColumn: @"col3_UB");

        return pipeline;
    }
}