// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraderProxy;

#nullable disable

namespace TraderProxy.Migrations
{
    [DbContext(typeof(ProxyEfDbContext))]
    [Migration("20230111195336_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TraderProxy.Entities.MarketStateSnap", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Actual")
                        .HasColumnType("float");

                    b.Property<double?>("BestAsk")
                        .HasColumnType("float");

                    b.Property<double?>("BestBid")
                        .HasColumnType("float");

                    b.Property<double>("BigVolume")
                        .HasColumnType("float");

                    b.Property<double?>("Change")
                        .HasColumnType("float");

                    b.Property<double?>("High")
                        .HasColumnType("float");

                    b.Property<string>("InstrumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Low")
                        .HasColumnType("float");

                    b.Property<double?>("PartChange")
                        .HasColumnType("float");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<int>("Trade")
                        .HasColumnType("int");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("DateTime");

                    b.ToTable("MarketStateSnaps");
                });
#pragma warning restore 612, 618
        }
    }
}
